export const portfolios = [
    {
      company: "Drygon Consulting Inc.",
      link:"https://drygon.ca",
      description: ["ReactJS", 
                    "Redux",
                    "Redux-devtools",
                    "Redux-Form",
                    "React-Router",
                    "Javascript", 
                    "HTML5", 
                    "CSS3", 
                    "ReactStrap",
                    "Bootstrap4",
                    "Firebase", 
                    "Firebase Functions",
                    "NodeMailer",
                    "Google Analytic",
                    "Github", ],
      image:"./drygon.png",
      date:"March, 2017"
    },
  {
    company: "Ann S. Xie Professional Corporation",
  link: "https://annsxie.firebaseapp.com",
  description: ["ReactJS",
                "React-Router",
                "Redux-form",
                "Redux-devtools",
                "reline",
                "styled-components",
                "Prettier",
                "Javascript", 
                "HTML5", 
                "CSS3", 
                "Firebase", 
                "Github", 
                "gh-pages"],
image:"./annsxie-logo.png",
date:"August, 2017"
},
  {
    company: "Zihuijie.io Blog",
  link:"https://zihuijie.io",
  description: ["ReactJS", 
                "Javascript", 
                "HTML5", 
                "CSS3", 
                "Semantic-Ui-React",
                "Gatsby",
                "MarkDown",
                "Firebase", 
                "Github", 
                "gh-pages"],
image: "./code-flower.png",
date:"August, 2017"
},
  ]