export const sectionlist = [
  {title: 'Time Line',
  summary:'my work experience'},
  {title: 'Presentation',
  summary:'presentation from job'},
  {title: 'Training',
  summary:'training delivered'},
  {title: 'Useful Resources',
  summary:'some userful resources you might be interested'},
]

export const summary = 'I have worked for EPC industry for over 15 years, traveled many countries and worked with different clients.'
export const timelines =[
  {company: 'Self-employed',
  date:'Nov 2015',
 title:'Web Development & Data analyst',
 desc:'I like to learn and build. I build website and mobile apps in React use Google firebase as backend. I also love data analyst in python. ',
},
{company: 'Devon Energy',
date:'Apr 2013',
title:'Data analyst & Material Management',
desc:'I support engineering data exchange, build interface and data clean up. Also I developed utitilies to plan SCM activites, maintain cost, and plan packaging.',
},
{company: 'Bantrel Co.',
date:'Aug 2010',
title:'Data analyst & Material Management',
desc:'I designed and programmed ISO and Tag database to maintain tag transfer, inventory and interface to engineering design tools. I also support SCM interface to SAP and AP system. ',
},
{company: 'Petro-Canada',
date:'Jan 2008',
title:'Senior IS Specialist.',
desc:'I worked as IS sustainment specialist for Information plant project, support Bentley Lifecycle Data warehouse application.',
},
{company: 'Bantrel Co.',
date:'Dec 2004',
title:'Procurement Systems Technical Lead',
desc:'I lead procurement systems team, support system integration with engineering and AP systems, troubleshoot interface issues, train users, develop SOP.',
},
{company: 'COINs',
date:'Jan 2002',
title:'Consultant',
desc:'I provided business and IT consultancy in financial and procurement modules for clients to improve their business processes towards a more efficient and profitable direction.'
},
{company: 'Bechtel International',
date:'Aug 1996',
desc:'System Analyst',
desc:'I provided both IT and SCM system support, built web interface for inventory management and reporting services.'
},
]

